Repository GDSC-DGU/2025-APAC-SolutionChallenge-Globook, pull requests merged in 2025-05, with the labels that each got.

#15 Feature/#14 - Implements BookReader screen UI
  globook_client/assets/icons/svg/font-size.svg
  globook_client/assets/icons/svg/font.svg
  globook_client/assets/icons/svg/highlight.svg
  globook_client/assets/icons/svg/pause.svg
  globook_client/lib/app/config/app_pages.dart
  globook_client/lib/app/config/app_routes.dart
  globook_client/lib/app/config/color_system.dart
  globook_client/lib/app/utility/log_util.dart
  globook_client/lib/presentation/view/reader/reader_screen.dart
  globook_client/lib/presentation/view/reader/widget/reader_app_bar.dart
  globook_client/lib/presentation/view/reader/widget/reader_bottom_bar.dart
  globook_client/lib/presentation/view/reader/widget/reader_content.dart
  globook_client/lib/presentation/view_model/reader/reader_binding.dart
  globook_client/lib/presentation/view_model/reader/reader_view_model.dart
  globook_client/pubspec.lock
  globook_client/pubspec.yaml
Labels: FE, Feature

#23 Feature/#21 - Implement User Authentication and Authorization with Spring Security and JWT
  globook_server/.gitignore
  globook_server/build.gradle
  globook_server/src/main/java/org/gdsc/globook/application/UserRepository.java
  globook_server/src/main/java/org/gdsc/globook/core/annotation/AuthenticationPrincipal.java
  globook_server/src/main/java/org/gdsc/globook/core/constant/Constants.java
  globook_server/src/main/java/org/gdsc/globook/core/exception/GlobalErrorCode.java
  globook_server/src/main/java/org/gdsc/globook/core/interceptor/post/ResponseInterceptor.java
  globook_server/src/main/java/org/gdsc/globook/core/interceptor/pre/AuthenticationPrincipalArgumentResolver.java
  globook_server/src/main/java/org/gdsc/globook/core/interceptor/pre/AuthenticationPrincipalInterceptor.java
  globook_server/src/main/java/org/gdsc/globook/core/security/config/PasswordConfig.java
  globook_server/src/main/java/org/gdsc/globook/core/security/config/SecurityConfig.java
  globook_server/src/main/java/org/gdsc/globook/core/security/filter/JwtAuthenticationFilter.java
  globook_server/src/main/java/org/gdsc/globook/core/security/filter/JwtExceptionFilter.java
  globook_server/src/main/java/org/gdsc/globook/core/security/handler/AbstractFailureResponse.java
  globook_server/src/main/java/org/gdsc/globook/core/security/handler/JwtAccessDeniedHandler.java
  globook_server/src/main/java/org/gdsc/globook/core/security/handler/JwtAuthEntryPoint.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/CustomUserDetails.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/JwtAuthenticationToken.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/JwtToken.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/JwtUserInfo.java
  globook_server/src/main/java/org/gdsc/globook/core/security/manager/CustomAuthenticationManager.java
  globook_server/src/main/java/org/gdsc/globook/core/security/provider/JwtAuthenticationProvier.java
  globook_server/src/main/java/org/gdsc/globook/core/security/provider/UsernamePasswordAuthenticationProvider.java
  globook_server/src/main/java/org/gdsc/globook/core/security/service/CustomUserDetailsService.java
  globook_server/src/main/java/org/gdsc/globook/core/util/JwtUtil.java
  globook_server/src/main/java/org/gdsc/globook/domain/ELanguage.java
  globook_server/src/main/java/org/gdsc/globook/domain/ELoginProvider.java
  globook_server/src/main/java/org/gdsc/globook/domain/EUserRole.java
  globook_server/src/main/java/org/gdsc/globook/domain/User.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/AuthController.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/TestController.java
Labels: BE, Feature

#27 Feature/#26 - Create JPA Domain Entites - File, Book, Paragraph, UserBook and Related Methods
  globook_server/src/main/java/org/gdsc/globook/domain/Book.java
  globook_server/src/main/java/org/gdsc/globook/domain/ECategory.java
  globook_server/src/main/java/org/gdsc/globook/domain/EFileStatus.java
  globook_server/src/main/java/org/gdsc/globook/domain/File.java
  globook_server/src/main/java/org/gdsc/globook/domain/Paragraph.java
  globook_server/src/main/java/org/gdsc/globook/domain/User.java
  globook_server/src/main/java/org/gdsc/globook/domain/UserBook.java
Labels: BE, Feature

#28 Feature/#25 - Implement App Sign Up and Login with Google Oauth2.0 and Email based Authentication
  globook_server/src/main/java/org/gdsc/globook/application/repository/UserRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/response/OAuth2UserInfo.java
  globook_server/src/main/java/org/gdsc/globook/application/service/AuthService.java
  globook_server/src/main/java/org/gdsc/globook/core/constant/Constants.java
  globook_server/src/main/java/org/gdsc/globook/core/exception/GlobalErrorCode.java
  globook_server/src/main/java/org/gdsc/globook/core/security/service/CustomUserDetailsService.java
  globook_server/src/main/java/org/gdsc/globook/core/util/JwtUtil.java
  globook_server/src/main/java/org/gdsc/globook/core/util/OAuth2Util.java
  globook_server/src/main/java/org/gdsc/globook/core/util/RandomNicknameUtil.java
  globook_server/src/main/java/org/gdsc/globook/core/util/RandomPasswordUtil.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/AuthController.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/TestController.java
  globook_server/src/main/java/org/gdsc/globook/presentation/request/SignInRequestDto.java
  globook_server/src/main/java/org/gdsc/globook/presentation/request/SignUpRequestDto.java
Labels: BE, Feature

#34 Feature/#29 - Implement Bookstore Domain Feature
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookDetailResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookListResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookRandomListResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookSearchResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookThumbnailResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/BookRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/UserBookRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/UserRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/service/AuthService.java
  globook_server/src/main/java/org/gdsc/globook/application/service/BookStoreService.java
  globook_server/src/main/java/org/gdsc/globook/application/service/UserBookService.java
  globook_server/src/main/java/org/gdsc/globook/core/config/WebMvcConfig.java
  globook_server/src/main/java/org/gdsc/globook/core/constant/Constants.java
  globook_server/src/main/java/org/gdsc/globook/core/exception/GlobalErrorCode.java
  globook_server/src/main/java/org/gdsc/globook/core/interceptor/pre/AuthenticationPrincipalArgumentResolver.java
  globook_server/src/main/java/org/gdsc/globook/core/interceptor/pre/AuthenticationPrincipalInterceptor.java
  globook_server/src/main/java/org/gdsc/globook/core/security/filter/JwtAuthenticationFilter.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/CustomUserDetails.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/JwtAuthenticationToken.java
  globook_server/src/main/java/org/gdsc/globook/core/security/info/JwtUserInfo.java
  globook_server/src/main/java/org/gdsc/globook/core/security/provider/JwtAuthenticationProvier.java
  globook_server/src/main/java/org/gdsc/globook/core/security/service/CustomUserDetailsService.java
  globook_server/src/main/java/org/gdsc/globook/core/util/JwtUtil.java
  globook_server/src/main/java/org/gdsc/globook/domain/ECategory.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/Book.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/File.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/Paragraph.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/User.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/UserBook.java
  globook_server/src/main/java/org/gdsc/globook/domain/type/ECategory.java
  globook_server/src/main/java/org/gdsc/globook/domain/type/EFileStatus.java
  globook_server/src/main/java/org/gdsc/globook/domain/type/ELanguage.java
  globook_server/src/main/java/org/gdsc/globook/domain/type/ELoginProvider.java
  globook_server/src/main/java/org/gdsc/globook/domain/type/EUserRole.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/AuthController.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/BookStoreController.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/TestController.java
Labels: BE, Feature

#38 Feature/#31 - Implement retrieve Favorite book List & downloaded book list
  globook_server/src/main/java/org/gdsc/globook/application/dto/BookSearchResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/FavoriteBookListResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/dto/FavoriteBookThumbnailResponseDto.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/UserBookRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/service/UserBookService.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/UserBookController.java
Labels: BE, Feature

#43 Refactor/#39 - Refactoring translator bottom sheet
  globook_client/lib/domain/enum/EbookCategory.dart
  globook_client/lib/domain/enum/EttsGender.dart
  globook_client/lib/domain/model/tts_character.dart
  globook_client/lib/presentation/widget/book_read_setting_bottom_sheet.dart
Labels: FE, Feature, Refactoring

#50 Feature/#41 - Implement Read translated book details and modify UserBook Download API
  globook_server/build.gradle
  globook_server/src/main/java/org/gdsc/globook/application/port/TranslateMarkdownPort.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/BookRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/service/BookStoreService.java
  globook_server/src/main/java/org/gdsc/globook/application/service/PdfFetchService.java
  globook_server/src/main/java/org/gdsc/globook/application/service/UserBookService.java
  globook_server/src/main/java/org/gdsc/globook/core/exception/GlobalErrorCode.java
  globook_server/src/main/java/org/gdsc/globook/domain/entity/UserBook.java
  globook_server/src/main/java/org/gdsc/globook/presentation/controller/BookStoreController.java
Labels: BE, Feature

#56 Refactor/#55 - Add parallel Gemini response processing with retry backoff for 503 errors
  globook_server/src/main/java/org/gdsc/globook/application/port/TTSPort.java
  globook_server/src/main/java/org/gdsc/globook/application/repository/ParagraphRepository.java
  globook_server/src/main/java/org/gdsc/globook/application/service/ParagraphService.java
  globook_server/src/main/java/org/gdsc/globook/core/util/RetryUtils.java
  globook_server/src/main/java/org/gdsc/globook/infrastructure/adapter/MarkdownToParagraphAdapter.java
  globook_server/src/main/java/org/gdsc/globook/infrastructure/adapter/TTSAdapter.java
  globook_server/src/main/java/org/gdsc/globook/infrastructure/adapter/TranslateMarkdownAdapter.java
Labels: Refactoring

#59 Feature/#58 - Implements reader screen Pagenation scroll logic
  globook_client/assets/icons/svg/new-font.svg
  globook_client/lib/data/provider/reader/reader_provider.dart
  globook_client/lib/data/provider/reader/reader_provider_impl.dart
  globook_client/lib/data/repository/home/home_repository_impl.dart
  globook_client/lib/domain/usecase/reader/reader_usecase.dart
  globook_client/lib/presentation/view/reader/reader_screen.dart
  globook_client/lib/presentation/view/reader/widget/reader_app_bar.dart
  globook_client/lib/presentation/view/reader/widget/reader_content.dart
  globook_client/lib/presentation/view/upload/upload_screen.dart
  globook_client/lib/presentation/view_model/reader/reader_view_model.dart
Labels: FE, Feature
